### ISSUE TITLE
Sourcemap shouldn't be included

### ISSUE THREAD

**Issue by EliteEngineer0** [fakexale/engine-next#3]
Like what da hell dog why !

@denispionicul im still waiting for some fire to release

**Comment by fakexale** [comment]
# Fixed.

**Comment by EliteEngineer0** [comment]
The **.gitignore** file is used to ignore files that are not meant to be tracked by Git. If a file is already being tracked adding it to the **.gitignore** won't not have any effect. 

In our case, the **sourcemap.json** file is already being tracked by Git, which is why it is not being ignored despite being listed in the **.gitignore** file. To stop tracking the file, you can use the `git rm --cached` command to remove the file from the repository without deleting it from your file system. After removing the file, you have to stage the deletion of **sourcemap.json**
